engines:
  csslint:
      enabled: true
  eslint:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
    - lib
exclude_paths:
  - bin
  - dist
  - node_modules
  - src
  - doc
  - .git
  - .idea
  - CHANGELOG.md
  - LICENSE.md
  - "**.json"