language: node_js
node_js: '6'
install: npm install
branches:
  only:
    - master
deploy:
  provider: npm
  email: 'info@crazysquirrel.ru'
  api_key: '443206b0-d7ea-47eb-89ca-9ff2e6ec246b'
  skip_cleanup: true
  on:
    branch: master
